name: Build
        
on:
  push:
    branches:
      - main
  pull_request: {}


jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - name: Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          registry-url: "https://registry.npmjs.org"
      - name: install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build project
        run: npm run build
      - name: Run Gravity
        run: npm run gravityci "dist/**/*"
        env:
          GRAVITY_TOKEN: ${{ secrets.GRAVITY_TOKEN }}
          GRAVITY_HOST: ${{ vars.GRAVITY_HOST }}
