name: Build
        
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]


jobs:
  build:
    runs-on: ubuntu-latest
    name: with Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Node.js
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
      - name: install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: my-artifact
          path: dist
