name: Build
        
on:
  push:
    branches:
      - main
  pull_request: {}


jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          registry-url: "https://registry.npmjs.org"
      - name: install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build project
        run: npm run build
      - name: Run Gravity
        run: npm run gravityci "dist/**/*"
        env:
          GRAVITY_TOKEN: ${{ secrets.GRAVITY_TOKEN }}
          GRAVITY_HOST: ${{ vars.GRAVITY_HOST }}
